### PR TITLE
fix(ascii2d): changed to ascii2d GET interface, fix #26

### LINKED ISSUE #26: koishi 4.17.2 下 ascii2d 搜索报错
koishi版本：`4.17.2`
所有依赖均已更新至最新

搜索ascii2d显示`访问失败。`，报错如下：
Clipboard - 2024-03-09 15 40 17

### PR DESCRIPTION
**Pull request by Container-Zero**
修改为 ascii2d 的 GET 接口，以节省请求资源，并规避高版本 koishi 下 Formdata 报错而无法使用 ascii2d 接口的错误。

### CODE REVIEW

File: src/ascii2d.ts [hunk 1]
```diff
@@ -1,22 +1,18 @@
...
-    form.append('file', await http.get(url, { responseType: 'stream' }))
-    const colorHTML = await http.post(`${baseURL}/search/file`, form, {
+    const colorHTML = await http.get(`${baseURL}/search/url/${encodeURIComponent(url)}`,{
       headers: {
-        'User-Agent': 'PostmanRuntime/7.29.0',
-        ...form.getHeaders(),
+          'User-Agent': 'PostmanRuntime/7.29.0',
       },
-    })
+    });
```
Comment (MaikoTan) [inline src/ascii2d.ts:15]:
```suggestion
    })
```

**Review by MaikoTan — CHANGES_REQUESTED** [review]

**Review by MaikoTan — COMMENTED** [review]
Looks good to me, could you change the koishi version in package.json to 4.17.0 or newer for forcing the new api for fetching resources?

**Comment by Container-Zero** [comment]
> Looks good to me, could you change the koishi version in package.json to 4.17.0 or newer for forcing the new api for fetching resources?

Modified.

**Review by shigma — APPROVED** [review]
